name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Copy scram and baremux to public
        run: |
          cp -r node_modules/@mercuryworkshop/scramjet/dist public/scram
          cp -r node_modules/@mercuryworkshop/bare-mux/dist public/baremux
          cp -r node_modules/@mercuryworkshop/libcurl-transport/dist public/libcurl

      - name: Deploy public folder to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
